apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingsystemc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankingsystemc
  template:
    metadata:
      labels:
        app: bankingsystemc
    spec:
      containers:
      - name: bankingsystemc
        image: davidgarcial/bankingsystemc:latest
        env:
        - name: KAFKA_URL
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "transaction-topic"
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://mongodb:27017"
        - name: MONGODB_DATABASE
          value: "cplus"
        - name: MONGODB_COLLECTION
          value: "accounts"

---
apiVersion: v1
kind: Service
metadata:
  name: bankingsystemc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankingsystemc
